spring:
  application:
    name:
  datasource: # mysql ???
    url: jdbc:mysql://localhost:3306/cinema_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8    # ?????? URL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password: cinema!@#$1234
  mustache:
    suffix: .html
    servlet:
      cache: false


server:
  port: 8184
